@startuml jerarquiaTecnicas

hide empty members
hide circle

class M_I {
            **Patrón dominante**
            ----
            • Bucles con índices
            • Modificación in-situ
            • Arrays mutables
            ----
            Ejemplo:
            Burbuja, Inserción, Heapsort    
}
class M_R {
            **Patrón híbrido**
            ----
            • Recursión con efectos
            • Modificación durante el retroceso
            ----
            Ejemplo:
            Quicksort in-place    
}
class I_I {
            **Patrón funcional**
            ----
            • Bucles con acumulador
            • Copia en cada paso
            • Estructuras persistentes
            ----
            Ejemplo: fold/reduce
            sobre listas inmutables
        }
class I_R {
            **Patrón puramente funcional**
            ----
            • Recursión sin efectos
            • Nuevas estructuras
              en cada llamada
            ----
            Ejemplo: Mergesort
            funcional, map/filter
        }

together {
    class "Algoritmo general" as General {
        Entrada → Transformación → Salida
        ---
        Restricciones:
        · Composición de llamadas
        · Mutabilidad del estado
    }
}

class "Iterativo" as Iter {
    Estado explícito
    Flujo secuencial
}

class "Recursivo" as Rec {
    Estado implícito en pila
    Flujo compositivo
}

class "Mutable" as Mut {    
    Modificación directa
    Eficiencia espacial
}

class "Inmutable" as Inmut {
    Transformaciones puras
    Razonamiento composicional
}

Iter <-r- General : ¿Cómo se gestiona
Rec <-l- General: el flujo de control?

General -u-> Mut : ¿Cómo se gestiona
General -d-> Inmut: el estado?

M_I -d- Iter
M_I -r- Mut

M_R -l- Mut
M_R -d- Rec

I_I -u- Iter
I_I -r- Inmut

I_R -u- Rec
I_R -l- Inmut


' note right of RestComp
'     Dimensión 1:
'     ¿Cómo se gestiona
'     el flujo de control?
' end note
'
' note right of RestMut
'     Dimensión 2:
'     ¿Cómo se gestiona
'     el estado?
' end note
'
' note bottom of General
'     Estas dimensiones son ortogonales:
'     genera 4 combinaciones posibles
'     (Iterativo-Mutable, Iterativo-Inmutable,
'     Recursivo-Mutable, Recursivo-Inmutable)
' end note

@enduml